version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-app
        restart: unless-stopped
        ports:
            -   "9000:9000"
        volumes:
            - .:/var/www/html
        networks:
            - my-network
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: nginx-app
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - my-network
        depends_on:
            - php
            - db
        links:
            -   db
    db:
        image: mysql:8
        container_name: mysql-app
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
